apiVersion: v1
kind: Pod
metadata:
  name: testPod

spec:
  containers:
    - name: testContainer
      image: kangclzjc/fio
      command: ["fio", "-filename=/test/testfile -iodepth 1 -thread -rw=randwrite -ioengine=libaio -bs=16k -size=2G -rate=10M -numjobs=1 -runtime=604800 -time_based -groupd_reporting -name=test"]
      resources:
        limits:
          cpu: "0.2"
          memory: "100Mi"
        requests:
          cpu: "0.2"
          memory: "100Mi"