apiVersion: v1
kind: Pod
metadata:
  name: %podName%
  annotations:
    blockio.kubernetes.io/container.stress.rbps: "600M"
    blockio.kubernetes.io/container.stress.wbps: "600M"
    #blockio.resources.beta.kubernetes.io/container.stress: high-prio
spec:
  containers:
    - name: %containerName%
      image: kangclzjc/fio
      command: ["fio", "-filename=%filename% -iodepth %iodepth% -thread -rw=%rw% -ioengine=%ioengine% -bs=%bs% -size=%size% -rate=%rate% -numjobs=%numjobs% -runtime=%runtime% -time_based -groupd_reporting -name=%name%"]
      resources:
        limits:
          cpu: "0.2"
          memory: "100Mi"
        requests:
          cpu: "0.2"
          memory: "100Mi"
